# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

require:
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - ".simplecov"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "app/admin/**/*"
    - "config/environments/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Style/HashSyntax:
  EnforcedShorthandSyntax: either
